version: '2'

services:
  supermarket:    
    container_name: supermarket
    image: supermarket
    build: .
    volumes:
      - .:/var/www
    networks:
      - main_network

  redis:
    container_name: supermarket_redis
    image: redis
    ports:
        - "6379"
    networks:
        - main_network

networks:
  main_network:
    driver: bridge
